name: lorem_ipsum_jp
description: It is a package to generate random text easily, quickly and dynamically.
version: 0.0.1
repository: https://github.com/duchdtran2706/jp_lorem_ipsum.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
